---
# yamllint disable rule:line-length

creation_rules:

  - path_regex: src/hosts/boschic/secrets/[^/]+.yaml$
    key_groups:
      - age:
          - age1wes6w27jntng7t0fl2scuz8l0s556e4m3x3q8qfczgah90kyfs3shuqvvl  # boschic
          - age15yyjuhudx0qaxrgshap4uwylvc6gek5dev7wsvc0zn32v6easp4qmyffmg  # <cdom>
        pgp:
          - 64604147C434F65EC306A21F135EEDD0F71934F3

  - path_regex: src/hosts/hodgepodge/secrets/[^/]+.yaml$
    key_groups:
      - age:
          - age1saydygdkg49p6g34ylds3m666x0nsr2f8clwcggsn9essqdkfqjsq9a25w  # hodgepodge
          - age15yyjuhudx0qaxrgshap4uwylvc6gek5dev7wsvc0zn32v6easp4qmyffmg  # <cdom>
        pgp:
          - 64604147C434F65EC306A21F135EEDD0F71934F3

  - path_regex: src/hosts/riebeck/secrets/[^/]+.yaml$
    key_groups:
      - age:
          - age13mjzm8jq3jfg62kdz98jrz8nas6s6shhm5u8240xdmjkpxky5v9sl72jhy  # riebeck
          - age15yyjuhudx0qaxrgshap4uwylvc6gek5dev7wsvc0zn32v6easp4qmyffmg  # <cdom>
        pgp:
          - 64604147C434F65EC306A21F135EEDD0F71934F3

  - path_regex: src/hosts/ryosuke/secrets/[^/]+.yaml$
    key_groups:
      - age:
          - age14rlwkyskyfz65vrvu2n4v3vslqvuqc8uk7vjsre9n52zpnhke30svsjvak  # ryosuke
          - age15yyjuhudx0qaxrgshap4uwylvc6gek5dev7wsvc0zn32v6easp4qmyffmg  # <cdom>
        pgp:
          - 64604147C434F65EC306A21F135EEDD0F71934F3

  - path_regex: src/hosts/tuuvok/secrets/[^/]+.yaml$
    key_groups:
      - age:
          - age19kn70a9r8m40kf7xw0gkme07gvxzmgncsvh2dfnpdrp5d82xefcsc9ezzm  # tuuvok
          - age15yyjuhudx0qaxrgshap4uwylvc6gek5dev7wsvc0zn32v6easp4qmyffmg  # <cdom>
        pgp:
          - 64604147C434F65EC306A21F135EEDD0F71934F3

  - path_regex: src/hosts/tuvix/secrets/[^/]+.yaml$
    key_groups:
      - age:
          - age1mufuvfqdnvzmvc4rkx7aq2fwqg7m8xa8lfm33e6k3zhgqd2elaasghe64d  # tuvix
          - age18yqe2svh9ck0san5uzthh6m774r2450hhz4ustguza2l8nttk30qxvtpf4  # <cdom@tuvix>
          - age15yyjuhudx0qaxrgshap4uwylvc6gek5dev7wsvc0zn32v6easp4qmyffmg  # <cdom>
        pgp:
          - 64604147C434F65EC306A21F135EEDD0F71934F3

  - path_regex: src/users/cdom/secrets/[^/]+.yaml$
    key_groups:
      - age:
          - age1up0p4xs0lze04acxrlxqj374ymu0dfkmc6adz2psmlz8g57ddv2qvf6pd4  # <seadoom@boschic>
          - age1msqfwt34d3gd5eaj54mmkffyac8hlrkwstwgfqp9ztf6yyreqg9qn7a63w  # <seadoom@hodgepodge>
          - age1xaxgeky7xtxuv8en508fr330wxaje0rdcr73j23kla70dt8lvsdqy33ypz  # <cdom@riebeck>
          - age19une89quzx4jt36hndrdp5ghr43845dndctfta206f7ts5ucsyjqt0l3pm  # <cdom@ryosuke>
          - age1a6wqjd7kf7hqq2v9fljnnz3qvn05l696yz9y74tdjd6d2rjyavvqt352h5  # <cdom@tuuvok>
          - age18yqe2svh9ck0san5uzthh6m774r2450hhz4ustguza2l8nttk30qxvtpf4  # <cdom@tuvix>
          - age15yyjuhudx0qaxrgshap4uwylvc6gek5dev7wsvc0zn32v6easp4qmyffmg  # <cdom>
        pgp:
          - 64604147C434F65EC306A21F135EEDD0F71934F3

  - path_regex: secrets/[^/]+.yaml$
    key_groups:
      - age:
          - age15yyjuhudx0qaxrgshap4uwylvc6gek5dev7wsvc0zn32v6easp4qmyffmg  # <cdom>
          - age1wes6w27jntng7t0fl2scuz8l0s556e4m3x3q8qfczgah90kyfs3shuqvvl  # boschic
          - age1saydygdkg49p6g34ylds3m666x0nsr2f8clwcggsn9essqdkfqjsq9a25w  # hodgepodge
          - age13mjzm8jq3jfg62kdz98jrz8nas6s6shhm5u8240xdmjkpxky5v9sl72jhy  # riebeck
          - age14rlwkyskyfz65vrvu2n4v3vslqvuqc8uk7vjsre9n52zpnhke30svsjvak  # ryosuke
          - age19kn70a9r8m40kf7xw0gkme07gvxzmgncsvh2dfnpdrp5d82xefcsc9ezzm  # tuuvok
        pgp:
          - 64604147C434F65EC306A21F135EEDD0F71934F3
