# SPDX-FileCopyrightText: (C) 2026 Chris Montgomery <chmont@protonmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
matches:
  - replace: 'Temple University'
    trigger: ';w;tu'
  - replace: 'Klein College of Media and Communication'
    trigger: ';w;kc'
