[widget.clock]
capsule = true
capsule_padding = 4
capsule_radius = 0
font_family = "Unifont"
font_scale = 1.0600000000000001
scale = 1.25

[bar]
order = ["default"]

[bar.default]
border_width = 1.0
capsule_radius = 0
center = []
concave_edge_corners = false
end = ["media", "tray", "spacer_2", "group:g2", "spacer_3", "clock"]
margin_ends = 0
padding = 0
radius = 0
start = ["group:g1", "workspaces"]
thickness = 26

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "surface_variant"
id = "g1"
members = ["session", "control-center", "wallpaper", "launcher"]
opacity = 1.0
padding = 6.0
radius = 0.0

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
enabled = true
fill = "surface"
id = "g2"
members = [
  "clipboard",
  "notifications",
  "network",
  "bluetooth",
  "volume",
  "battery",
]
opacity = 1.0
padding = 6.0
radius = 0.0
