#!/usr/bin/env bash

# SPDX-FileCopyrightText: (C) 2026 Chris Montgomery <chmont@protonmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

release=$(curl -s https://api.github.com/repos/shytikov/pragmasevka/releases/latest)

oldVersion=$(nix-instantiate --eval -E 'with import ../.. {}; lib.getVersion pragmasevka-bin' | tr -d '"')
version=$(echo "$release" | jq -r .tag_name | tr -d v)

if test "$oldVersion" = "$version"; then
    echo "New version same as old version, nothing to do." >&2
    exit 0
fi

sed -i "s/$oldVersion/$version/" bin-package.nix

{
    echo '# This file was autogenerated. DO NOT EDIT!'
    echo '{'
    # FIXME: make sure we are not grabbing the nerdfonts version
    for asset in $(echo "$release" | jq -r '.assets[].name | select(startswith("PkgTTC"))'); do
        printf '  %s = "%s";\n' \
            "$(echo "$asset" | sed -r "s/^PkgTTC-(.*)-$version.zip$/\1/")" \
            "$(nix-prefetch-url "https://github.com/shytikov/pragmasevka/releases/download/v$version/$asset")"
    done
    echo '}'
} >variants.nix
